### ISSUE TITLE
Documentation: Add "Enable module" instructions

### ISSUE THREAD

**Issue by stephencapellic** [wire-drupal/wire#2]
I was going through the Counter tutorial [https://wire-drupal.com/docs/quickstart] and got this error after adding `{{ wire('counter') }}` to my page Twig file.

> Drupal\Component\Plugin\Exception\PluginNotFoundException: The "counter" plugin does not exist. Valid plugin IDs for Drupal\wire\Plugin\WirePluginManager are: counter in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of /var/www/html/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

I then realized that I hadn't yet enabled the module I just created. I then did:

```
drush en counter
drush cr
```

Then reloaded the page and it worked! 

I think your documentation could be made clearer by adding instructions to enable the module on these pages:

1. https://wire-drupal.com/docs/quickstart
2. https://wire-drupal.com/docs/rendering-components

**Comment by hugronaphor** [comment]
Hmm, I'm considering this out-of-scope as docs walks through explaining how to create and use components. Where it is included it's not something to assume. it could have been added in a theme too.

**Comment by stephencapellic** [comment]
I think the context of where I ran into the problem has clouded the main point I was trying to make: The documentation doesn't say to enable the module that was just created by `drush generate wire`.

If you still disagree that's fine, just felt that there was a miscommunication. 😄

**Comment by hugronaphor** [comment]
OK I got you now, agree and added a note in the docs.
